# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["develop"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build from develop branch and deploy to gh-pages branch
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install Angular CLI
        run: npm install -g @angular/cli
        
      - name: Build Angular application from develop branch
        run: npm run build -- --base-href=/angular-admin-panel/
        
      - name: Verify build output
        run: |
          echo "Checking build output..."
          ls -la dist/
          ls -la dist/angular-admin-panel/browser/ || echo "Browser folder not found"
          echo "Checking index.html for base href..."
          cat dist/angular-admin-panel/browser/index.html | grep -i "base href" || echo "Base href not found"
        
      - name: Copy dist/browser content to gh-pages branch and publish
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/angular-admin-panel/browser
          publish_branch: gh-pages
          force_orphan: true
